#sprint9
kasisaki/java-filmorate pull request #1
Opened 2023-01-04 22:20 UTC by kasisaki

2023-01-05 19:42 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но надо немного доработать

2023-01-05 19:42 UTC, krylov-sergey-sergeevich commented on HELP.md
> +# Getting Started
Надо бы добавить этот файл в гитигнор и удалить из PR

2023-01-05 19:42 UTC, krylov-sergey-sergeevich commented on mvnw
> +#!/bin/sh
Надо бы добавить этот файл в гитигнор и удалить из PR

2023-01-05 19:42 UTC, krylov-sergey-sergeevich commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
Надо бы добавить этот файл в гитигнор и удалить из PR

2023-01-05 19:42 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>1.18.24</version>
Можешь изучить что такое блок properties в maven и туда вынести версию

2023-01-05 19:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final LocalDate dateLimit = LocalDate.of(1895, 12, 28);
Эту переменную лучше вынести в класс Constants

2023-01-05 19:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new javax.validation.ValidationException("Login must not contain spaces");
Лучше создать свою ошибку для валидация чем бросать внутреннюю из какой то библиотеки

2023-01-05 19:42 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
В ТЗ описано что тесты должны проверить функционал валидация

2023-01-07 14:47 UTC, krylov-sergey-sergeevich requested changes
Привет, те правки которые вижу по ним окей, а тестов так и нет.

Кину пример как подсказку:
```java
import javax.validation.*;

ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
validator = factory.getValidator();

@Test

public void invalidName() {

	film = Film.builder().name("")
	
			.description("qweq")
			
			.duration(120)
			
			.releaseDate(LocalDate.of(1999, 12, 12))
			
			.build();
	
	violations = validator.validate(film);
	
	  
	
	assertFalse(violations.isEmpty(), violations.toString());
	
	violations.clear();

}
```

2023-01-07 14:47 UTC, krylov-sergey-sergeevich commented on pom.xml
> +	<properties> <!-- не уверен, что требовалось, но кое-что вынес сюда -->
Все верно!

2023-01-07 14:47 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws ValidationException {
А зачем добавлено throws ValidationException? Тут и далее

2023-01-08 10:40 UTC, kasisaki commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws ValidationException {
Validationexception тут был потомком Throwable.
Сделал его потомком RuntimeException
Затем вообще реализовал без выкидывания исключений. Покажу в новой версии.

2023-01-08 10:43 UTC, kasisaki commented on pom.xml
> +	<properties> <!-- не уверен, что требовалось, но кое-что вынес сюда -->
По поводу тестов. Твой комментарий про тесты вылетел из головы. Тестировал через предоставленный в ТЗ скрипт для Postman.
Попробую написать "встроенные тесты" и  представлю в следующей итерации.

2023-01-13 05:59 UTC, kasisaki commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Сергей, тесты сделал, запушил. Но не могу проверку пройти... выдает ошибку 253 и требует, чтобы я сделал репу публичной хотя она и так таковой является. Не знаю как на ревью направить((

2023-01-15 08:11 UTC, krylov-sergey-sergeevich approved these changes
Привет, не без погрешностей, но работа уже похожа на то что можно зачесть - зачет!

Просьба то что отметил доработать по пути к 10 дз и особенно учесть про дату тк это может еще аффектить аннотацию и лучше сразу сделать хорошо (если получится).

Удачи с следующим дщ =)

2023-01-15 08:11 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<?> create(@Valid @RequestBody Film film) {
ResponseEntity<?> Почему знак вопроса а не Film? В других местах аналогично

2023-01-15 08:11 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ArrayList<Film> findAll() {
Можно лучше: `List<Film>` в других местах в контроллерах аналогично

2023-01-15 08:11 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/util/Constants.java
> +    public final static String DATE_LIMIT = "1895-12-27";
А может чтобы не усложнять себе жизнь мы тут сразу объект в формате даты будем хранить а не строки?

2023-01-15 09:21 UTC, kasisaki commented on src/main/java/ru/yandex/practicum/filmorate/util/Constants.java
> +    public final static String DATE_LIMIT = "1895-12-27";
Изначально я так и хотел. Однако эта константа у меня используется для валидации и система не дала мне использовать тип ни LocaDate, ни DateTime, ни ZonedDateTime для валидации. Точное сообщение не помню, но если нужно могу повторить и привести это сообщение.
т.к. константа с типом LocalDate мне пока не нужна для других целей я ее пока убрал вообще.

2023-01-15 09:24 UTC, kasisaki commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<?> create(@Valid @RequestBody Film film) {
Забыл поменять. Сделаю

2023-01-15 09:24 UTC, kasisaki commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ArrayList<Film> findAll() {
Ок

2023-01-15 09:26 UTC, merged