#Sprint10 Add friends likes
kasisaki/java-filmorate pull request #2
Opened 2023-01-29 21:50 UTC by kasisaki

2023-01-30 22:23 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохая работа, давай поправим то что отметил и еще пару моментов:

1) **Учесть и поправить нейминг методов:** get - это или получение объекта или исключение, find - это или объект или null
2) Давай вместо конструктора будем аннотацию из ломбока использовать  @requiredargsconstructor 
3) Мы не имеем право пользоваться исключениями из фреймворка для наших бизнес целей, надо создать свои исключения для всех ситуаций
4) Можно, но не обязательно: почитать о ExceptionHandler и сделать обработку ошибок
5) А валидация разве вся которая необходима есть? Ощущение что чего-то не хватает, но могу ошибаться

Буду ждать с правками, если что пиши в пачке =)

2023-01-30 22:23 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Давай вместо конструктора будем аннотацию из ломбока использовать  @requiredargsconstructor

2023-01-30 22:23 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> likedFilms = new HashSet<>();
А зачем тут лайки они же в фильме есть

2023-01-30 22:23 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (foundFilm == null) throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Film not found");
Мы не имеем право пользоваться исключениями из фреймворка для наших бизнес целей, надо создать свои исключения для всех ситуаций

2023-01-30 22:23 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/util/Constants.java
> +    т.к. константа с типом LocalDate мне пока не нужна для других целей я ее пока убрал вообще.
А для валидации?

2023-02-02 21:58 UTC, kasisaki commented on src/main/java/ru/yandex/practicum/filmorate/util/Constants.java
> +    т.к. константа с типом LocalDate мне пока не нужна для других целей я ее пока убрал вообще.
Только для валидации и используется. Про валидацию я написал выше))

2023-02-03 06:33 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки  - зачет!

На счет исключений в будущем все равно придется создать более специализированные исключения. Поэтому рекомендую сразу думать о том чтобы для каждого типа ситуаций создавать исключение, например
UserNotFound(id)
FilmNotFound(id)

2023-02-05 18:16 UTC, merged